#pyqt的ui文件转换为py文件
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QMainWindow,QApplication
#qt窗口UI设计
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 830)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget1 = QtWidgets.QWidget(MainWindow)
        self.widget1.setObjectName("widget1")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.widget1)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 40, 801, 75))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.row2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.row2.setContentsMargins(0, 0, 0, 0)
        self.row2.setSpacing(10)
        self.row2.setObjectName("row2")
        self.toolButton_6 = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_6.sizePolicy().hasHeightForWidth())
        self.toolButton_6.setSizePolicy(sizePolicy)
        self.toolButton_6.setMinimumSize(QtCore.QSize(18, 17))
        self.toolButton_6.setStyleSheet("font: 25 11pt \"3ds\";")
        self.toolButton_6.setObjectName("toolButton_6")
        self.row2.addWidget(self.toolButton_6)
        self.toolButton_2 = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMinimumSize(QtCore.QSize(18, 17))
        self.toolButton_2.setStyleSheet("font: 25 11pt \"3ds\";")
        self.toolButton_2.setObjectName("toolButton_2")
        self.row2.addWidget(self.toolButton_2)
        self.toolButton_5 = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        self.toolButton_5.setMinimumSize(QtCore.QSize(18, 17))
        self.toolButton_5.setStyleSheet("font: 25 11pt \"3ds\";")
        self.toolButton_5.setObjectName("toolButton_5")
        self.row2.addWidget(self.toolButton_5)
        self.toolButton_4 = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_4.sizePolicy().hasHeightForWidth())
        self.toolButton_4.setSizePolicy(sizePolicy)
        self.toolButton_4.setMinimumSize(QtCore.QSize(18, 17))
        self.toolButton_4.setStyleSheet("font: 25 11pt \"3ds\";")
        self.toolButton_4.setObjectName("toolButton_4")
        self.row2.addWidget(self.toolButton_4)
        self.toolButton_3 = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMinimumSize(QtCore.QSize(18, 17))
        self.toolButton_3.setStyleSheet("font: 25 11pt \"3ds\";")
        self.toolButton_3.setObjectName("toolButton_3")
        self.row2.addWidget(self.toolButton_3)
        self.Open = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Open.sizePolicy().hasHeightForWidth())
        self.Open.setSizePolicy(sizePolicy)
        self.Open.setMinimumSize(QtCore.QSize(18, 17))
        self.Open.setStyleSheet("font: 25 11pt \"3ds\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/TripleWs/.designer/res/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Open.setIcon(icon)
        self.Open.setAutoRepeat(False)
        self.Open.setObjectName("Open")
        self.row2.addWidget(self.Open)
        self.backgroung_main = QtWidgets.QListView(self.widget1)
        self.backgroung_main.setGeometry(QtCore.QRect(0, 0, 951, 701))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.backgroung_main.setFont(font)
        self.backgroung_main.setMouseTracking(False)
        self.backgroung_main.setAutoFillBackground(False)
        self.backgroung_main.setStyleSheet("background-color:rgb(227, 238 ,240)")
        self.backgroung_main.setLineWidth(0)
        self.backgroung_main.setMovement(QtWidgets.QListView.Snap)
        self.backgroung_main.setObjectName("backgroung_main")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget1)
        self.graphicsView.setGeometry(QtCore.QRect(340, 190, 531, 341))
        self.graphicsView.setObjectName("graphicsView")
        self.tableWidget = QtWidgets.QTableWidget(self.widget1)
        self.tableWidget.setGeometry(QtCore.QRect(10, 170, 251, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        self.backgroung_main.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.graphicsView.raise_()
        self.tableWidget.raise_()
        MainWindow.setCentralWidget(self.widget1)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1047, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(43)
        sizePolicy.setVerticalStretch(43)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setMinimumSize(QtCore.QSize(58, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menuBar.setFont(font)
        self.menuBar.setAutoFillBackground(False)
        self.menuBar.setStyleSheet("background-color:rgb(191, 219, 255)")
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.menuFile.sizePolicy().hasHeightForWidth())
        self.menuFile.setSizePolicy(sizePolicy)
        self.menuFile.setMinimumSize(QtCore.QSize(10, 10))
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuNetwork = QtWidgets.QMenu(self.menuBar)
        self.menuNetwork.setObjectName("menuNetwork")
        self.menuSend_to_PACS = QtWidgets.QMenu(self.menuNetwork)
        self.menuSend_to_PACS.setObjectName("menuSend_to_PACS")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuBrowse_images = QtWidgets.QMenu(self.menuView)
        self.menuBrowse_images.setObjectName("menuBrowse_images")
        self.menuImage = QtWidgets.QMenu(self.menuBar)
        self.menuImage.setObjectName("menuImage")
        self.menuMeasure = QtWidgets.QMenu(self.menuBar)
        self.menuMeasure.setObjectName("menuMeasure")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.Bar_File = QtWidgets.QToolBar(MainWindow)
        self.Bar_File.setObjectName("Bar_File")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.Bar_File)
        self.Bar_Image = QtWidgets.QToolBar(MainWindow)
        self.Bar_Image.setObjectName("Bar_Image")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.Bar_Image)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.New_Window = QtWidgets.QAction(MainWindow)
        self.New_Window.setObjectName("New_Window")
        self.Open_Window = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../res/row1/row1.1/window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Open_Window.setIcon(icon1)
        self.Open_Window.setObjectName("Open_Window")
        self.Scan_for = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../res/magnifier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Scan_for.setIcon(icon2)
        self.Scan_for.setObjectName("Scan_for")
        self.Download_from_DICOM_server = QtWidgets.QAction(MainWindow)
        self.Download_from_DICOM_server.setCheckable(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/TripleWs/.designer/res/cloud-download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Download_from_DICOM_server.setIcon(icon3)
        self.Download_from_DICOM_server.setObjectName("Download_from_DICOM_server")
        self.Network_activity = QtWidgets.QAction(MainWindow)
        self.Network_activity.setObjectName("Network_activity")
        self.actionOpen_CD_DVD = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../res/cd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_CD_DVD.setIcon(icon4)
        self.actionOpen_CD_DVD.setObjectName("actionOpen_CD_DVD")
        self.actionOpen_ZIP_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_ZIP_file.setObjectName("actionOpen_ZIP_file")
        self.Copy_to_Folder = QtWidgets.QAction(MainWindow)
        self.Copy_to_Folder.setObjectName("Copy_to_Folder")
        self.Anoymize = QtWidgets.QAction(MainWindow)
        self.Anoymize.setObjectName("Anoymize")
        self.Print = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../res/printer打印.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Print.setIcon(icon5)
        self.Print.setObjectName("Print")
        self.Exit = QtWidgets.QAction(MainWindow)
        self.Exit.setCheckable(True)
        self.Exit.setObjectName("Exit")
        self.To_a_picture = QtWidgets.QAction(MainWindow)
        self.To_a_picture.setObjectName("To_a_picture")
        self.To_a_video_file = QtWidgets.QAction(MainWindow)
        self.To_a_video_file.setObjectName("To_a_video_file")
        self.To_a_DICOM_file = QtWidgets.QAction(MainWindow)
        self.To_a_DICOM_file.setObjectName("To_a_DICOM_file")
        self.To_a_text_file = QtWidgets.QAction(MainWindow)
        self.To_a_text_file.setObjectName("To_a_text_file")
        self.To_clipbord = QtWidgets.QAction(MainWindow)
        self.To_clipbord.setObjectName("To_clipbord")
        self.actionScroll_Tool = QtWidgets.QAction(MainWindow)
        self.actionScroll_Tool.setObjectName("actionScroll_Tool")
        self.actionCine = QtWidgets.QAction(MainWindow)
        self.actionCine.setObjectName("actionCine")
        self.actionZoom = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../res/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon6)
        self.actionZoom.setStatusTip("")
        self.actionZoom.setObjectName("actionZoom")
        self.actionDICOM_Tags = QtWidgets.QAction(MainWindow)
        self.actionDICOM_Tags.setObjectName("actionDICOM_Tags")
        self.Current_Image = QtWidgets.QAction(MainWindow)
        self.Current_Image.setObjectName("Current_Image")
        self.Current_Series = QtWidgets.QAction(MainWindow)
        self.Current_Series.setObjectName("Current_Series")
        self.Current_study = QtWidgets.QAction(MainWindow)
        self.Current_study.setObjectName("Current_study")
        self.Current_patient = QtWidgets.QAction(MainWindow)
        self.Current_patient.setObjectName("Current_patient")
        self.All_patient = QtWidgets.QAction(MainWindow)
        self.All_patient.setObjectName("All_patient")
        self.Advanced = QtWidgets.QAction(MainWindow)
        self.Advanced.setObjectName("Advanced")
        self.actionNext_Image = QtWidgets.QAction(MainWindow)
        self.actionNext_Image.setObjectName("actionNext_Image")
        self.actionPreviou_Image = QtWidgets.QAction(MainWindow)
        self.actionPreviou_Image.setObjectName("actionPreviou_Image")
        self.actionAfter_10_Images = QtWidgets.QAction(MainWindow)
        self.actionAfter_10_Images.setObjectName("actionAfter_10_Images")
        self.actionBefore_10_Images = QtWidgets.QAction(MainWindow)
        self.actionBefore_10_Images.setObjectName("actionBefore_10_Images")
        self.actionNext_series = QtWidgets.QAction(MainWindow)
        self.actionNext_series.setObjectName("actionNext_series")
        self.actionPreviou_series = QtWidgets.QAction(MainWindow)
        self.actionPreviou_series.setObjectName("actionPreviou_series")
        self.actionFull_Screen = QtWidgets.QAction(MainWindow)
        self.actionFull_Screen.setObjectName("actionFull_Screen")
        self.actionSplit_Screen = QtWidgets.QAction(MainWindow)
        self.actionSplit_Screen.setObjectName("actionSplit_Screen")
        self.actionSync = QtWidgets.QAction(MainWindow)
        self.actionSync.setObjectName("actionSync")
        self.actionDICOM_Broswer = QtWidgets.QAction(MainWindow)
        self.actionDICOM_Broswer.setObjectName("actionDICOM_Broswer")
        self.actionDICOM_Tags_Pane = QtWidgets.QAction(MainWindow)
        self.actionDICOM_Tags_Pane.setObjectName("actionDICOM_Tags_Pane")
        self.actionStatus_Bar = QtWidgets.QAction(MainWindow)
        self.actionStatus_Bar.setObjectName("actionStatus_Bar")
        self.actionTool_Bar = QtWidgets.QAction(MainWindow)
        self.actionTool_Bar.setObjectName("actionTool_Bar")
        self.actionTheme = QtWidgets.QAction(MainWindow)
        self.actionTheme.setObjectName("actionTheme")
        self.actionWindowing = QtWidgets.QAction(MainWindow)
        self.actionWindowing.setObjectName("actionWindowing")
        self.actionFlip_and_Rotate = QtWidgets.QAction(MainWindow)
        self.actionFlip_and_Rotate.setObjectName("actionFlip_and_Rotate")
        self.actionFilters = QtWidgets.QAction(MainWindow)
        self.actionFilters.setObjectName("actionFilters")
        self.actionImage_resize = QtWidgets.QAction(MainWindow)
        self.actionImage_resize.setObjectName("actionImage_resize")
        self.actionCopy_to_clipboard = QtWidgets.QAction(MainWindow)
        self.actionCopy_to_clipboard.setObjectName("actionCopy_to_clipboard")
        self.Distance_D = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../res/distance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Distance_D.setIcon(icon7)
        self.Distance_D.setObjectName("Distance_D")
        self.Angle_A = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../res/Angle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Angle_A.setIcon(icon8)
        self.Angle_A.setObjectName("Angle_A")
        self.Ellipse = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../res/Ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Ellipse.setIcon(icon9)
        self.Ellipse.setObjectName("Ellipse")
        self.Rectangle_R = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../res/rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Rectangle_R.setIcon(icon10)
        self.Rectangle_R.setObjectName("Rectangle_R")
        self.Open_curve = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../res/curve.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Open_curve.setIcon(icon11)
        self.Open_curve.setObjectName("Open_curve")
        self.Free_Hand = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../res/hand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Free_Hand.setIcon(icon12)
        self.Free_Hand.setObjectName("Free_Hand")
        self.Calibration = QtWidgets.QAction(MainWindow)
        self.Calibration.setObjectName("Calibration")
        self.Arrow = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../res/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Arrow.setIcon(icon13)
        self.Arrow.setObjectName("Arrow")
        self.Text = QtWidgets.QAction(MainWindow)
        self.Text.setObjectName("Text")
        self.Hide_area = QtWidgets.QAction(MainWindow)
        self.Hide_area.setObjectName("Hide_area")
        self.Edit = QtWidgets.QAction(MainWindow)
        self.Edit.setObjectName("Edit")
        self.INFO = QtWidgets.QAction(MainWindow)
        self.INFO.setObjectName("INFO")
        self.Show_Measurement_and_Anotations = QtWidgets.QAction(MainWindow)
        self.Show_Measurement_and_Anotations.setObjectName("Show_Measurement_and_Anotations")
        self.actionMeasure_and_Annotation_Option = QtWidgets.QAction(MainWindow)
        self.actionMeasure_and_Annotation_Option.setObjectName("actionMeasure_and_Annotation_Option")
        self.actionAbou_Us = QtWidgets.QAction(MainWindow)
        self.actionAbou_Us.setObjectName("actionAbou_Us")
        self.actionSupport_Us = QtWidgets.QAction(MainWindow)
        self.actionSupport_Us.setObjectName("actionSupport_Us")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.actionOptions.setFont(font)
        self.actionOptions.setObjectName("actionOptions")
        self.actionCustomize = QtWidgets.QAction(MainWindow)
        self.actionCustomize.setObjectName("actionCustomize")
        self.actionTag_Dictionary = QtWidgets.QAction(MainWindow)
        self.actionTag_Dictionary.setObjectName("actionTag_Dictionary")
        self.actionTag_Manager = QtWidgets.QAction(MainWindow)
        self.actionTag_Manager.setObjectName("actionTag_Manager")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../res/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon14)
        self.actionHelp.setObjectName("actionHelp")
        self.menuExport.addAction(self.To_a_picture)
        self.menuExport.addAction(self.To_a_video_file)
        self.menuExport.addAction(self.To_a_DICOM_file)
        self.menuExport.addAction(self.To_a_text_file)
        self.menuExport.addAction(self.To_clipbord)
        self.menuFile.addAction(self.New_Window)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.Scan_for)
        self.menuFile.addAction(self.Open_Window)
        self.menuFile.addAction(self.actionOpen_CD_DVD)
        self.menuFile.addAction(self.actionOpen_ZIP_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.Copy_to_Folder)
        self.menuFile.addAction(self.Anoymize)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.Print)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.Exit)
        self.menuSend_to_PACS.addAction(self.Current_Image)
        self.menuSend_to_PACS.addAction(self.Current_Series)
        self.menuSend_to_PACS.addAction(self.Current_study)
        self.menuSend_to_PACS.addAction(self.Current_patient)
        self.menuSend_to_PACS.addAction(self.All_patient)
        self.menuSend_to_PACS.addSeparator()
        self.menuSend_to_PACS.addAction(self.Advanced)
        self.menuNetwork.addAction(self.Download_from_DICOM_server)
        self.menuNetwork.addAction(self.Network_activity)
        self.menuNetwork.addAction(self.menuSend_to_PACS.menuAction())
        self.menuBrowse_images.addAction(self.actionNext_Image)
        self.menuBrowse_images.addAction(self.actionPreviou_Image)
        self.menuBrowse_images.addAction(self.actionAfter_10_Images)
        self.menuBrowse_images.addAction(self.actionBefore_10_Images)
        self.menuBrowse_images.addSeparator()
        self.menuBrowse_images.addAction(self.actionNext_series)
        self.menuBrowse_images.addAction(self.actionPreviou_series)
        self.menuView.addAction(self.actionDICOM_Tags)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionScroll_Tool)
        self.menuView.addAction(self.menuBrowse_images.menuAction())
        self.menuView.addAction(self.actionCine)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoom)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFull_Screen)
        self.menuView.addAction(self.actionSplit_Screen)
        self.menuView.addAction(self.actionSync)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDICOM_Broswer)
        self.menuView.addAction(self.actionDICOM_Tags_Pane)
        self.menuView.addAction(self.actionStatus_Bar)
        self.menuView.addAction(self.actionTool_Bar)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionTheme)
        self.menuImage.addAction(self.actionWindowing)
        self.menuImage.addAction(self.actionFlip_and_Rotate)
        self.menuImage.addAction(self.actionFilters)
        self.menuImage.addSeparator()
        self.menuImage.addAction(self.actionImage_resize)
        self.menuImage.addSeparator()
        self.menuImage.addAction(self.actionCopy_to_clipboard)
        self.menuMeasure.addAction(self.Distance_D)
        self.menuMeasure.addAction(self.Angle_A)
        self.menuMeasure.addAction(self.Ellipse)
        self.menuMeasure.addAction(self.Rectangle_R)
        self.menuMeasure.addAction(self.Open_curve)
        self.menuMeasure.addAction(self.Free_Hand)
        self.menuMeasure.addSeparator()
        self.menuMeasure.addAction(self.Calibration)
        self.menuMeasure.addSeparator()
        self.menuMeasure.addAction(self.Arrow)
        self.menuMeasure.addAction(self.Text)
        self.menuMeasure.addAction(self.Hide_area)
        self.menuMeasure.addSeparator()
        self.menuMeasure.addAction(self.Edit)
        self.menuMeasure.addSeparator()
        self.menuMeasure.addAction(self.INFO)
        self.menuMeasure.addSeparator()
        self.menuMeasure.addAction(self.Show_Measurement_and_Anotations)
        self.menuMeasure.addSeparator()
        self.menuMeasure.addAction(self.actionMeasure_and_Annotation_Option)
        self.menuTools.addAction(self.actionOptions)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCustomize)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionTag_Dictionary)
        self.menuTools.addAction(self.actionTag_Manager)
        self.menuHelp.addAction(self.actionAbou_Us)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionSupport_Us)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuNetwork.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuImage.menuAction())
        self.menuBar.addAction(self.menuMeasure.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.Bar_File.addAction(self.Open_Window)
        self.Bar_File.addAction(self.actionOpen_CD_DVD)
        self.Bar_File.addAction(self.Scan_for)
        self.Bar_File.addSeparator()
        self.Bar_File.addAction(self.Print)
        self.Bar_File.addAction(self.actionHelp)
        self.Bar_Image.addAction(self.Distance_D)
        self.Bar_Image.addAction(self.Angle_A)
        self.Bar_Image.addAction(self.Ellipse)
        self.Bar_Image.addAction(self.Rectangle_R)
        self.Bar_Image.addAction(self.Open_curve)
        self.Bar_Image.addAction(self.Free_Hand)
        self.Bar_Image.addAction(self.Arrow)
        self.Bar_Image.addAction(self.actionZoom)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MedImago"))
        self.toolButton_6.setToolTip(_translate("MainWindow", "Ctrl+O"))
        self.toolButton_6.setText(_translate("MainWindow", "Open"))
        self.toolButton_2.setText(_translate("MainWindow", "Open CD/VCD"))
        self.toolButton_5.setText(_translate("MainWindow", "Scan For DICOM"))
        self.toolButton_4.setText(_translate("MainWindow", "Export To Images"))
        self.toolButton_3.setText(_translate("MainWindow", "Export To Videos"))
        self.Open.setText(_translate("MainWindow", "Print"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Patient"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Age"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sex"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuNetwork.setTitle(_translate("MainWindow", "Network"))
        self.menuSend_to_PACS.setTitle(_translate("MainWindow", "Send to PACS"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuBrowse_images.setTitle(_translate("MainWindow", "Browse images"))
        self.menuImage.setTitle(_translate("MainWindow", "Image"))
        self.menuMeasure.setTitle(_translate("MainWindow", "Measure"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.Bar_File.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.Bar_Image.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.New_Window.setText(_translate("MainWindow", "New Window   Ctrl+N"))
        self.Open_Window.setText(_translate("MainWindow", "Open Window"))
        self.Open_Window.setIconText(_translate("MainWindow", "Ctrl + O"))
        self.Open_Window.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.Scan_for.setText(_translate("MainWindow", "Scan for             Ctrl+F"))
        self.Download_from_DICOM_server.setText(_translate("MainWindow", "Download from DICOM server..."))
        self.Network_activity.setText(_translate("MainWindow", "Network activity\n"
""))
        self.actionOpen_CD_DVD.setText(_translate("MainWindow", "Open CD/DVD"))
        self.actionOpen_ZIP_file.setText(_translate("MainWindow", "Open ZIP file"))
        self.Copy_to_Folder.setText(_translate("MainWindow", "Copy to Folder"))
        self.Anoymize.setText(_translate("MainWindow", "Anoymize"))
        self.Print.setText(_translate("MainWindow", "Print"))
        self.Exit.setText(_translate("MainWindow", "Exit"))
        self.To_a_picture.setText(_translate("MainWindow", "To a picture              Shift+P"))
        self.To_a_video_file.setText(_translate("MainWindow", "To a video file           Shift+V"))
        self.To_a_DICOM_file.setText(_translate("MainWindow", "To a DICOM file        Shift+D"))
        self.To_a_text_file.setText(_translate("MainWindow", "To a text file              Shift+T"))
        self.To_clipbord.setText(_translate("MainWindow", "To clipbord               Shift+P"))
        self.actionScroll_Tool.setText(_translate("MainWindow", "Scroll Tool"))
        self.actionCine.setText(_translate("MainWindow", "Cine"))
        self.actionZoom.setText(_translate("MainWindow", "Zoom"))
        self.actionZoom.setToolTip(_translate("MainWindow", "Magnifier"))
        self.actionDICOM_Tags.setText(_translate("MainWindow", "DICOM Tags Management"))
        self.Current_Image.setText(_translate("MainWindow", "Current Image"))
        self.Current_Series.setText(_translate("MainWindow", "Current Series"))
        self.Current_study.setText(_translate("MainWindow", "Current study"))
        self.Current_patient.setText(_translate("MainWindow", "Current patient"))
        self.All_patient.setText(_translate("MainWindow", "All patient"))
        self.Advanced.setText(_translate("MainWindow", "Advanced"))
        self.actionNext_Image.setText(_translate("MainWindow", "Next Image"))
        self.actionPreviou_Image.setText(_translate("MainWindow", "Previou Image"))
        self.actionAfter_10_Images.setText(_translate("MainWindow", "After 10 Images"))
        self.actionBefore_10_Images.setText(_translate("MainWindow", "Before 10 Images"))
        self.actionNext_series.setText(_translate("MainWindow", "Next series"))
        self.actionPreviou_series.setText(_translate("MainWindow", "Previou series"))
        self.actionFull_Screen.setText(_translate("MainWindow", "Full Screen"))
        self.actionSplit_Screen.setText(_translate("MainWindow", "Split Screen"))
        self.actionSync.setText(_translate("MainWindow", "Sync"))
        self.actionDICOM_Broswer.setText(_translate("MainWindow", "DICOM Broswer"))
        self.actionDICOM_Tags_Pane.setText(_translate("MainWindow", "DICOM Tags Pane"))
        self.actionStatus_Bar.setText(_translate("MainWindow", "Status Bar"))
        self.actionTool_Bar.setText(_translate("MainWindow", "Tool Bar"))
        self.actionTheme.setText(_translate("MainWindow", "Theme"))
        self.actionWindowing.setText(_translate("MainWindow", "Windowing"))
        self.actionFlip_and_Rotate.setText(_translate("MainWindow", "Flip and Rotate"))
        self.actionFilters.setText(_translate("MainWindow", "Filters"))
        self.actionImage_resize.setText(_translate("MainWindow", "Image resize             Shift+S"))
        self.actionCopy_to_clipboard.setText(_translate("MainWindow", "Copy to clipboard     Shift+C"))
        self.Distance_D.setText(_translate("MainWindow", "Distance    D"))
        self.Angle_A.setText(_translate("MainWindow", "Angle         A"))
        self.Angle_A.setToolTip(_translate("MainWindow", "Measure the Angle"))
        self.Ellipse.setText(_translate("MainWindow", "Ellipse"))
        self.Ellipse.setToolTip(_translate("MainWindow", "Draw a Ellipse"))
        self.Rectangle_R.setText(_translate("MainWindow", "Rectangle    R"))
        self.Rectangle_R.setToolTip(_translate("MainWindow", "Draw a Rectangle"))
        self.Rectangle_R.setStatusTip(_translate("MainWindow", "R"))
        self.Open_curve.setText(_translate("MainWindow", "Open curve"))
        self.Free_Hand.setText(_translate("MainWindow", "Free Hand"))
        self.Free_Hand.setToolTip(_translate("MainWindow", "Draw with ur mouse"))
        self.Calibration.setText(_translate("MainWindow", "Calibration"))
        self.Arrow.setText(_translate("MainWindow", "Arrow"))
        self.Text.setText(_translate("MainWindow", "Text"))
        self.Hide_area.setText(_translate("MainWindow", "Hide area"))
        self.Edit.setText(_translate("MainWindow", "Edit"))
        self.INFO.setText(_translate("MainWindow", "INFO"))
        self.Show_Measurement_and_Anotations.setText(_translate("MainWindow", "Show Measurement and Anotations"))
        self.actionMeasure_and_Annotation_Option.setText(_translate("MainWindow", "Measure and Annotation Option"))
        self.actionAbou_Us.setText(_translate("MainWindow", "About Us"))
        self.actionSupport_Us.setText(_translate("MainWindow", "Support Us"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionCustomize.setText(_translate("MainWindow", "Customize"))
        self.actionTag_Dictionary.setText(_translate("MainWindow", "Tag Dictionary"))
        self.actionTag_Manager.setText(_translate("MainWindow", "Tag Manager"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setToolTip(_translate("MainWindow", "How to USE"))
if __name__ == '__main__':
        app = QApplication(sys.argv)
        window = QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(window)
        window.show()
        sys.exit(app.exec_())
