# 设置系统名称
SET(CMAKE_SYSTEM_NAME Windows)

# 指定编译器
SET(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

# 设置查找根路径
SET(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)

# 调整查找程序的行为
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# 设置Qt目录
SET(QT_BINARY_DIR /usr/x86_64-w64-mingw32/bin) 